### PR TITLE
provide browser replacements after nuking snap

### PR DESCRIPTION
**Pull request by cobalt2727**

### CODE REVIEW

**Comment by theofficialgman** [comment]
instead of grepping for a name and making things hard. at some point I'll pull in the changes I made in multimc script for using version numbers
which should be more resistant to issues and future updates

**Comment by cobalt2727** [comment]
@theofficialgman am I good to merge this now or did you want to rework version detection first?

**Comment by theofficialgman** [comment]
don't merge yet, there is still some work to be done

**Comment by theofficialgman** [comment]
@cobalt2727 take a look at this again. Should be a lot easier to maintain and cleaner

**Comment by cobalt2727** [comment]
Looks good!

**Pull request merged**
