### PR TITLE
Add script for godot

### LINKED ISSUE #137: Add godot engine
Godot engine is fully functional on the switch, but it needs to be compiled from source. Raspberry pi builds don't work due to some kind of version issue.

In short: `sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm clang`

Edit /usr/bin/scons so the shebang says `/usr/bin/python3` instead of Python

Download godot tar.xz, I did godot 3.5.2 https://github.com/godotengine/godot/releases

Extract, change to directory and do `scons platform=x11 target=release_debug tools=yes use_llvm=yes CCFLAGS="-march=armv8-a+fp+simd" arch=arm64 -j4`. Instructions taken from https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi/blob/main/compiling/raspberry_pi_4.md

It will take 2 hours to compile. `use_llvm` is required, g++ has a linker error. I tested debugging games and clicking around and there were no issues, but I didn't test it super extensively. It seemed to handle GLES3 perfectly.

Or alternatively a download for compiled builds can be hosted, but I don't have anywhere to host builds.

### PR DESCRIPTION
**Pull request by SegoGithub**
This script currently doesn't support Fedora, but it should be simple to just check the distro and install the deps.
Should fix #137

### CODE REVIEW

**Comment by SegoGithub** [comment]
godot3 is already a package available in the fedora repos, doesn't need any modifications to run

**Comment by cobalt2727** [comment]
Can you take a look at the comments I left here when you get the chance?

**Comment by SegoGithub** [comment]
Sorry, I forgot about this. But I don't see any comments.

**Comment by cobalt2727** [comment]
@SegoGithub Still interested in this? My review comments should be visible by scrolling up in this conversation.

**Comment by cobalt2727** [comment]
after over a year I've finally discovered where GitHub was hiding the UI to publish pending review comments. apologies for the delay.

**Comment by SegoGithub** [comment]
It's alright, I've used the `lastversion` thing you've mentioned. Didn't even know it existed but seems like a very useful tool.
I've left the build flags unmodified as you've said it's for RythmLunatic.

**Comment by cobalt2727** [comment]
1. why are you manually installing stuff under /usr/ instead of /usr/local/ exactly?
2. what's this line for?
> sudo sed -i '1s/.*/#! \/usr\/bin\/python3/' /usr/bin/scons

**Comment by SegoGithub** [comment]
1. Since this script was written a really long time ago, I don't really know why I used /usr/ but I will change it to /usr/local/ since that's what should be used for manually compiled packages as I've found online.

2. That sed command is to make scons use Python 3 instead of Python 2, it changes the shebang in the first line of /usr/bin/scons from `#! /usr/bin/python` to `#! /usr/bin/python3`

**Comment by cobalt2727** [comment]
If I'm not mistaken, same thing applies for `/usr/share/` - put that stuff under `/usr/local/share/`, please

**Comment by SegoGithub** [comment]
Done! If someone can please test this because I currently do not have the facilities to do it right now.

**Comment by cobalt2727** [comment]
Figured - @SegoGithub please update this to use native flags instead

**Comment by SegoGithub** [comment]
Done!

**Comment by cobalt2727** [comment]
LGTM. Let's see if it [passes the build checks](https://github.com/cobalt2727/L4T-Megascript/actions/runs/10414255389)

**Pull request merged**
