### PR TITLE
Change name of THP disable code

### PR DESCRIPTION
**Pull request by Heath123**
TPL is a typo as far as I know (the videos are in THP format), and this is more descriptive

### CODE REVIEW

**Comment by cobalt2727** [comment]
It's been a while since I tested this myself but isn't "Fast Menu" the one that gets rid of the THP videos?
http://wiki.tockdom.com/wiki/THP_(File_Format)
http://wiki.tockdom.com/wiki/TPL_(File_Format)

**Comment by Heath123** [comment]
No, fast menu just speeds up the menu.

**Comment by Heath123** [comment]
https://4drclanforum.com/threads/mkwii-online-with-android-phones.4621/
> Why would I use TPL Disable? Do you mean THP Disable? When I would disable TPL, the game had no textures at all.

> Oh, you're right. I keep on confusing the two all the time. THP are the videos. TPL are the textures. THP does make lag in the menus, so thats why you would disable it.

**Comment by cobalt2727** [comment]
Ah, weird...
So wait - what's the difference between the two codes then?

**Comment by Heath123** [comment]
> Ah, weird...
> So wait - what's the difference between the two codes then?

Fast Menu changes the speed of transitions, and "TPL Disable" turns off the decoding of THP videos

**Pull request merged**
