### PR TITLE
add GPLv3 License

### PR DESCRIPTION
**Pull request by theofficialgman**
Hi all contributors we are looking for your approval on finally adding a license to this repository.
The license chosen is GPLv3.

If you could please all response with "I approve" then we can merge. Otherwise I will be forced to re-write all contributions in the code such that none of your original code remains.

I will go ahead and be the first one. I approve.

replied:
@cobalt2727 @Lugsole @Azkali @mrcmunir  @leonpano2006 @MasonT8198 @makinbacon21 @abyzma @Heath123 @EyeCantCU @SegoGithub

not replied:
@Fafabis @JerryWester @Dajokeisonu

### CODE REVIEW

**Comment by MasonT8198** [comment]
I approve.

**Comment by abyzma** [comment]
I approve, not like i contributed much lmao--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 4/26/23, 00:50 theofficialgman ***@***.***> wrote:

  Hi all contributors we are looking for your approval on finally adding a license to this repository. The license chosen is GPLV3. 
  If you could please all response with "I approve" then we can merge. Otherwise I will be forced to re-write all contributions in the code such that none of your original code remains. 
  I will go ahead and be the first one. I approve. 
  @cobalt2727 @Fafabis @Lugsole @Azkali @mrcmunir @EyeCantCU @leonpano2006 @SegoGithub @MasonT8198 @makinbacon21 @abyzma @JerryWester @Heath123 @Dajokeisonu 
   
  You can view, comment on, or merge this pull request online at: 
    https://github.com/cobalt2727/L4T-Megascript/pull/128 
  Commit Summary 
   
   8e08e3a add GPLv3 License 
   
  File Changes  
  (1 file) 
   
    A COPYING (674)  
   
  Patch Links: 
   
   https://github.com/cobalt2727/L4T-Megascript/pull/128.patch 
   https://github.com/cobalt2727/L4T-Megascript/pull/128.diff

**Comment by cobalt2727** [comment]
Naturally, I approve.

**Comment by makinbacon21** [comment]
approved

**Comment by Lugsole** [comment]
I approve

**Comment by Azkali** [comment]
I approve

**Comment by leonpano2006** [comment]
I approve

The Great Wizard Azkali ***@***.***> 於 2023年4月26日 週三 上午8:56寫道：

**Comment by Heath123** [comment]
I approve

**Comment by mrcmunir** [comment]
I approve

**Comment by theofficialgman** [comment]
after reviewing the remaining commits from the contributors that have not replied. only @EyeCantCU has contributions that have not already been fully been rewritten. with his approval this PR will be merged.

**Comment by SegoGithub** [comment]
I approve.

**Comment by EyeCantCU** [comment]
I approve

**Pull request merged**
