### PR TITLE
Barrier.sh

### PR DESCRIPTION
**Pull request by Dajokeisonu**

### CODE REVIEW

**Comment by theofficialgman** [comment]
looks good but it needs added to the gui_rebase as well
I'll do that by pushing to this PR in an hour or two

**Comment by cobalt2727** [comment]
Looks fine to me, I can tweak the formatting to match the other scripts later. You guys think this should go in the extras section or no?

**Comment by theofficialgman** [comment]
yeah extras is probably a better location
I can move it as well. just don't merge it yet

**Comment by cobalt2727** [comment]
Barrier seems to have a package in 20.10
Should we set up some basic version detection to just apt install it if possible?

**Comment by theofficialgman** [comment]
it has one in 18.04 as well...
but its broken and doesn't work
hence why we build it ourselves

**Comment by cobalt2727** [comment]
Ah okay

Do you guys know what the issue is/if it's been resolved in newer versions or if it's a device-specific problem?

**Comment by theofficialgman** [comment]
pretty sure its just really old and they don't update it hence its incompatible

on the github it does not list 18.04 as having any pacakage status

**Pull request merged**
