### PR TITLE
Update retropie_auto.sh

### PR DESCRIPTION
**Pull request by pancakers2001**
added sudo before running scripts

### CODE REVIEW

**Comment by theofficialgman** [comment]
should be unnecessary as the entire script was built and runs as sudo from core.sh, core_refactor.sh, and core_gui.sh

**Comment by pancakers2001** [comment]
> @pancakers2001 should be unnecessary as the entire script was built and runs as sudo from core.sh, core_refactor.sh, and core_gui.sh

image

If it did it wouldn't display this.

**Comment by cobalt2727** [comment]
core.sh syntax:
`  sudo bash -c "$(curl -s https://raw.githubusercontent.com/$repository_username/L4T-Megascript/$repository_branch/scripts/retropie_auto.sh)"
`
core_gui.sh syntax:
`      2) echo $PRIVATE | sudo -S curl -L https://raw.githubusercontent.com/$repository_username/L4T-Megascript/$repository_branch/scripts/retropie_auto.sh | sudo bash ;;
`
core_refactor.sh syntax:
`    15) echo $PRIVATE | sudo -S curl -L https://raw.githubusercontent.com/$repository_username/L4T-Megascript/$repository_branch/scripts/retropie_auto.sh | bash ;;
`

**Comment by cobalt2727** [comment]
the first one has bash marked as sudo and not curl, the second one has both marked as sudo, and the third one only has curl marked as sudo
i'm unfamiliar with which one of these three methods would be the right one

**Comment by theofficialgman** [comment]
yeah cobalt I did make a mistake there
pretty sure that curl doesn't need the sudo at all and just needs sudo before bash

**Pull request closed without merging**
