### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Lang-Kasempo**
Fix a typo and Flappy Bird description (Sorry Cobalt)

### CODE REVIEW

**Comment by cobalt2727** [comment]
fair haha
SRB2Kart is actually made by a separate team going by Kart Krew

**Comment by Lang-Kasempo** [comment]
The github repo is made by STJr

**Comment by cobalt2727** [comment]
well yeah there's a lot of overlap there

**Comment by Lang-Kasempo** [comment]
"Kart Krew is in no way affiliated with SEGA or Sonic Team. We do not claim ownership of any of SEGA's intellectual property used in SRB2."  _I don't know how to read~_

**Pull request merged**
