### PR TITLE
Add t194 support

### PR DESCRIPTION
**Pull request by leonpano2006**
added t194 prebuilt package

### CODE REVIEW

**Comment by theofficialgman** [comment]
There is no such package from https://github.com/Pi-Apps-Coders/box64-debs

**Comment by leonpano2006** [comment]
> There is no such package from https://github.com/Pi-Apps-Coders/box64-debs

https://github.com/ryanfortner/box64-debs/raw/master/debian/box64-tegra-t194_0.2.7+20240130.63428d0-1_arm64.deb

**Comment by leonpano2006** [comment]
> Wrong repo. Unused at pi-apps and the megascript due to frequent breakages.

Appears I need to find a way to add with that repo just for t194 and t234

**Comment by theofficialgman** [comment]
We are not interested in any new repos. Feel free to make a PR to https://github.com/Pi-Apps-Coders/box64-debs
t194 must be built at minimum on bionic as there are Bionic and Focal releases for it.
t234 must be built at minimum on focal as there are Focal and Jammy releases for it.

also, do a performance comparison between the generic build and the t194 tuned build. I think you will find zero benefit from the tuned build (or within measurement error). that is the reason why tuned builds have been low priority compared to compatibility and stability.

**Comment by leonpano2006** [comment]
> > Wrong repo. Unused at pi-apps and the megascript due to frequent breakages.
> 
> Appears I need to find a way to add with that repo just for t194 and t234
> (It have newer gcc at least for focal)
> 
> Specially, I'm planning to add t234 as well
> And t234 optimization can't be done on <=gcc-10
> Reason: `-mcpu/mtune=cortex-a78ae` including `cortex-a78` does not exist on <=gcc-10

Can you convert this to draft?
Until https://github.com/Pi-Apps-Coders/box64-debs PR is made

**Comment by leonpano2006** [comment]
> We are not interested in any new repos. Feel free to make a PR to https://github.com/Pi-Apps-Coders/box64-debs t194 must be built at minimum on bionic as there are Bionic and Focal releases for it. t234 must be built at minimum on Focal as there are Focal and Jammy releases for it.
> 
> also, do a performance comparison between the generic build and the t194 tuned build. I think you will find zero benefit from the tuned build (or within measurement error). that is the reason why tuned builds have been low priority compared to compatibility and stability.

https://github.com/Pi-Apps-Coders/box64-debs/pull/1

**Pull request closed without merging**
