### PR TITLE
AntiMicroX

### PR DESCRIPTION
**Pull request by JerryWester**
Please excuse the poor commit names

### CODE REVIEW

**Comment by theofficialgman** [comment]
I don't have any problems with the script itself but if we include this it needs to be taken with caution.
Anitmicrox is clearly an alternative to xserver-xorg-input-joystick (what users call "joycon mouse"). I would rather not have someone end up with both of these programs installed and running as that would cause a lot of unnecessary havoc.

I'll checkout antimicrox next week once I have some free time. For now, Cobalt, refrain from merging this as I'll come up with something to prevent the dual installation and push to the fork.

**Comment by JerryWester** [comment]
> Anitmicrox is clearly an alternative to xserver-xorg-input-joystick
Actually, I use both together without much issue, though clearly disabling one when using the other. Primarily, I use AntiMicroX for easy setup for browser-based games.

**Comment by cobalt2727** [comment]
Yeah it's definitely very nice, I'm just a bit hesitant since input remappers in general can break things very easily...


@theofficialgman I was gonna talk with you about this before looking at it since I still don't have hardware to test with and I thought you'd be offline for a while, but I'll leave this up to you. It's worth noting that with the other programs our script currently installs, all support controller inputs natively (even Minecraft with LambdaControls, which I really should finish my automated fabric installer for...)

**Comment by theofficialgman** [comment]
alright I've tested out antimicrox... and yeah its definitely not an outright replacement for  xserver-xorg-input-joystick (since that runs at the driver level instead of userspace). cpu usage is significantly higher with antimicrox running (35% on the anitmicrox thread at 306Mhz... compared to an immeasurable amount for xserver-xorg-input-joystick at the same frequency)

regardless I do think this is useful for some users. I'll move it to the extras category, squash and merge it later this week

**Comment by cobalt2727** [comment]
Sounds good to me - thanks for testing (I promise I'll buy that Nano soon...)

**Comment by theofficialgman** [comment]
oh sorry we needed to fix some things
I do want this PR still open... I attempted to merge it and move some files around and it went badly...
you will need to open a new PR
I have some changes though to request

**Comment by theofficialgman** [comment]
I think the script would be better written like this

```
#!/bin/bash

echo "This script will install AntiMicroX, an updated fork of AntiMicro and"
echo "a graphical program used to map gamepad keys to keyboard."

# Dependancies
sudo apt install -y git gcc cmake extra-cmake-modules \
    qttools5-dev qttools5-dev-tools libsdl2-dev \
    libxi-dev libxtst-dev libx11-dev itstool gettext

# Cloning
cd ~
rm -rf antimicrox
git clone https://github.com/AntiMicroX/antimicrox.git
cd antimicrox
mkdir build && cd build

# Building
cmake ..
cmake --build .

# Installing
sudo mv -f bin/antimicrox /usr/bin/

# Desktop File
sudo tee /usr/share/applications/antimicrox.desktop <<'EOF'
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=/usr/bin/antimicrox
Name=AntiMicroX
Icon=/usr/share/applications/antimicrox.png
Categories=System
EOF

sudo cp -f ~/antimicrox/src/images/antimicrox.png /usr/share/applications/

# Removing source
cd ~
rm -rf antimicrox```

**Pull request closed without merging**
