### PR TITLE
added start scripts for retropie for emulators/games/applications und…

### PR DESCRIPTION
**Pull request by theofficialgman**
…er ports

Had a modify a lot of scripts. I tried my best to follow the formatting of having an assets folder for every application/game/emulator. Haven't done dolphin yet since that one will be special and need to show in gc and wii and not ports

### CODE REVIEW

**Comment by theofficialgman** [comment]
hold, up give me 2 minutes, I forgot one thing

**Comment by cobalt2727** [comment]
shouldn't we use `/home/$USER/` or just plain old `~` instead of `$HOME`?

**Comment by theofficialgman** [comment]
I actually just copied what lang wrote so...

**Comment by cobalt2727** [comment]
hmm. well, if we start having issues with this in the future i'll know where to look first

**Pull request merged**
