### PR TITLE
allow for custom repository username and branch name for devs

### PR DESCRIPTION
**Pull request by theofficialgman**
For devs wanting to test their own forks for functionality or the probably-broken-let's-be-real-here branch. Follow these instructions to run your own branch/forks.

Set your variables then run the megascript (core.sh or core_gui.sh:

export repository_username=mygithubusername
export repository_branch=mytestingbranch
bash -c "$(curl -s "https://raw.githubusercontent.com/$repository_username/L4T-Megascript/$repository_branch/core.sh")"

### CODE REVIEW

**Comment by Lugsole** [comment]
Looks good. You just need to squash the commits into one. `git rebase -i HEAD~3`

**Review by Lugsole — CHANGES_REQUESTED** [review]
Please squash into one commit.

**Comment by theofficialgman** [comment]
oh trust me I know those commands I just forgot this time

**Review by Lugsole — APPROVED** [review]
Looks good.

**Review by Lugsole — APPROVED** [review]
Looks good!

**Review by Lugsole — APPROVED** [review]
Lets try this again.

**Comment by Lugsole** [comment]
Nope, my approval means nothing.

**Comment by theofficialgman** [comment]
yeah looks like only Cobalt is an approving reviewer

**Pull request merged**
