### PR TITLE
AntiMicroX 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by JerryWester**

### CODE REVIEW

**Comment by cobalt2727** [comment]
Did we ever figure out why it was using so much of the CPU?

**Comment by theofficialgman** [comment]
> Did we ever figure out why it was using so much of the CPU?

No, and its honestly expected to use CPU resources. its just that the xserver implementation is actually extremely simple and barebones. 35% of one thread at 305mhz isn't terrible and I assume its probably just something to do with how it handles making sure the mouse doesn't ever appear to lag. Barrier uses up to 10% (of one thread) at similar frequency doing similar things so its nor outrageous.

**Comment by theofficialgman** [comment]
my apologies again for taking so long to merge this PR

**Comment by theofficialgman** [comment]
@JerryWester you might want to take a look at how cmake works...
I've updated your script in the megascript to be compile 4X faster on switch and use the official .desktop file with man pages addes and whatnot.
calling the make install command does all of this for you as long as the developer has written a good cmakelists.txt https://github.com/AntiMicroX/antimicrox/blob/039894be1bb200f269c0ee689b32ade00fc73cfa/CMakeLists.txt#L507

**Comment by JerryWester** [comment]
Thanks for merging (and updating the script)!

**Pull request merged**
